/*
Nome: Application Incident
Link: https://dev96986.service-now.com/nav_to.do?uri=%2Fsc_cat_item_producer.do%3Fsys_id%3Db4e76dad079501101590f19d7c1ed035
*/

/** This script is executed before the Record is generated
 * `current`- GlideRecord produced by Record Producer
 * Don't use `current.update()` or `current.insert()` as the record is generated by Record Producer
 * Don't use `current.setValue('sys_class_name', 'xxx')` as this will trigger reparent flow and can cause data loss
 * Avoid `current.setAbortAction()` and generate a separate record
 * Use `producer.var1` to access variables
 */

/* Preenchimento automático dos campos da tabela com valores da variável */
current.caller_id = producer.solicitante;
current.category = 'software';

/* Cálculo da prioridade do incidente */
new global.IncidentPriority().calcPrioridade(current, producer.cmdb_ci, producer.business_service);